name: Build and Publish AWS S3 Proxy

on:
  push:
  # workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/^refs\/heads\//, '');
        continue-on-error: true
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker run \
           -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
           -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
           -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
           amazon/aws-cli ecr get-login-password |
          docker login \
            --username AWS \
            --password-stdin \
            "${AWS_ECR_S3_PROXY}"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
          AWS_ECR_S3_PROXY: "${{ secrets.AWS_ECR_S3_PROXY }}"
      - name: Docker build
        working-directory: ./
        run: |
          set -x
          docker build -f docker/linux/2.0/Dockerfile -t aws-s3-proxy .
      - name: Docker push
        working-directory: ./
        run: |
          set -eufxo pipefail
          image="${AWS_ECR_S3_PROXY}/infrastructure/aws-s3-proxy"
          git_hash=$(git reflog --format='%h' -1)
          head_ref="${{ github.head_ref }}"
          branch_ref="${{ steps.branch.outputs.result }}"
          branch=""
          [ -z "${head_ref}" ] || branch=${head_ref}
          [ -z "${branch_ref}" ] || branch=${branch_ref}
          tag_image="${image}:${git_hash}"
          docker tag aws-s3-proxy "${tag_image}"
          docker push "${tag_image}"
          [ -z "${branch}" ] || {
            tag_image="${image}:${branch}-${git_hash}"
            docker tag aws-s3-proxy "${tag_image}"
            docker push "${tag_image}"
          }
        env:
          AWS_ECR_S3_PROXY: "${{ secrets.AWS_ECR_S3_PROXY }}"